sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - liblapack-dev
            - libblas-dev
            - valgrind
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/extern/metis
          - $TRAVIS_BUILD_DIR/extern/SuiteSparse
          - $TRAVIS_BUILD_DIR/extern/mpich
          - $TRAVIS_BUILD_DIR/extern/hypre

install:
    - sh config/build_scripts/build_metis.sh;
    - sh config/build_scripts/build_suitesparse.sh;
    - sh config/build_scripts/build_mpich.sh;
    - export PATH=extern/mpich/bin:$PATH;
    - PATH=extern/mpich/bin:$PATH;
    - which mpic++;
    - which mpicc;
    - ls extern/mpich/bin;
    - sh config/build_scripts/build_hypre.sh;
    - sh config/build_scripts/build_linalg.sh;

script:
   - cd $TRAVIS_BUILD_DIR;

   # Build the library
   - sh config/build_extern.sh;

   # Run tests
   - CTEST_OUTPUT_ON_FAILURE=1 make test;
