sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - liblapack-dev
            - libblas-dev
            - valgrind
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/extern/astyle
          - $TRAVIS_BUILD_DIR/extern/metis
          - $TRAVIS_BUILD_DIR/extern/SuiteSparse
          - $TRAVIS_BUILD_DIR/extern/mpich
          - $TRAVIS_BUILD_DIR/extern/hypre
          - $TRAVIS_BUILD_DIR/extern/mfem
          - $TRAVIS_BUILD_DIR/extern/spe10
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - liblapack-dev
            - libblas-dev
            - valgrind
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/extern/astyle
          - $TRAVIS_BUILD_DIR/extern/metis
          - $TRAVIS_BUILD_DIR/extern/SuiteSparse
          - $TRAVIS_BUILD_DIR/extern/mpich
          - $TRAVIS_BUILD_DIR/extern/hypre
          - $TRAVIS_BUILD_DIR/extern/mfem
          - $TRAVIS_BUILD_DIR/extern/spe10
    - os: osx
      compiler: gcc
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/extern/astyle
          - $TRAVIS_BUILD_DIR/extern/mpich
          - $TRAVIS_BUILD_DIR/extern/hypre
          - $TRAVIS_BUILD_DIR/extern/mfem
          - $TRAVIS_BUILD_DIR/extern/spe10
    - os: osx
      compiler: clang
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/extern/astyle
          - $TRAVIS_BUILD_DIR/extern/mpich
          - $TRAVIS_BUILD_DIR/extern/hypre
          - $TRAVIS_BUILD_DIR/extern/mfem
          - $TRAVIS_BUILD_DIR/extern/spe10

before_install:
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/extern/metis/lib:$LD_LIBRARY_PATH; 
    - export LIBRARY_PATH=$TRAVIS_BUILD_DIR/extern/metis/lib:$LIBRARY_PATH; 
    - export PATH=$TRAVIS_BUILD_DIR/extern/mpich/bin:$PATH;
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install metis; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install suite-sparse; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install astyle; fi

install:
    - if [ ! -d extern/astyle/bin ] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        sh config/build_scripts/build_astyle.sh;
     else
        echo "Reusing cached astyle";
     fi;

    - if [ ! -d extern/metis/lib ] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        sh config/build_scripts/build_metis.sh;
     else
        echo "Reusing cached metis";
     fi;

    - if [ ! -d extern/SuiteSparse/lib ] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        sh config/build_scripts/build_suitesparse.sh;
     else
        echo "Reusing cached SuiteSparse-4.5.4";
     fi;

    - if [ ! -d extern/mpich/bin ]; then
        sh config/build_scripts/build_mpich.sh;
     else
        echo "Reusing cached mpich";
     fi;

    - if [ ! -d extern/hypre/lib ]; then
        sh config/build_scripts/build_hypre.sh;
     else
        echo "Reusing cached hypre-2.10.0b";
     fi;

    - if [ ! -d extern/mfem/lib ]; then
        sh config/build_scripts/build_mfem.sh;
     else
        echo "Reusing cached mfem";
     fi;

    - if [ ! -d extern/spe10 ]; then
        sh config/build_scripts/build_spe10.sh;
     else
        echo "Reusing cached spe10";
     fi;

    - sh config/build_scripts/build_linalg.sh;

script:
   - cd $TRAVIS_BUILD_DIR;

   # Build the library
   - sh config/extern_miniapps_build.sh;

   # Run tests
   - cd build;
   - CTEST_OUTPUT_ON_FAILURE=1 make test;
